export const DEFAULT_THEME: Record<string, any> = {
  brand: '#4340EA',
  brandHover: '#3533C4',
  brandLight: '#F4F3FF',
  border: '#D0D5DD',
  borderHover: '#4340EA',
  borderDisabled: '#E0E0E0',
  bgWhite: '#FFFFFF',
  bgDisabled: '#F5F5F5',
  bgDisabledChecked: '#E0E0E0',
  textPrimary: '#333333',
  textDisabled: '#999999',
  textTitle: '#1A1A2E',
  checkMark: '#FFFFFF',
  checkMarkDisabled: '#999999',
  containerWidth: 400,
  containerCornerRadius: 12,
  shadowColor: '#0000001A',
  shadowOffset: { x: 0, y: 4 },
  shadowRadius: 12,
  titleFont: { family: 'Inter', style: 'Bold' },
  titleSize: 18,
  labelFont: { family: 'Inter', style: 'Regular' },
  labelSize: 14,
  componentSize: 16,
  componentCornerRadius: 6,
  radioCornerRadius: 8,
  strokeWeight: 1.5,
  rowGap: 20,
  colLabelX: 50,
  containerPadding: 24,
  penPath: 'M12 0L13.4142 1.41421L5.20711 9.62132L0 4.41421L1.41421 3L5.20711 6.79289L12 0Z',
  ellipseSize: 6,
  ellipsePos: { x: 5, y: 5 },
  borderRadiusSm: 2,
  borderRadiusMd: 4,
  borderRadiusLg: 6,
  borderRadiusXl: 8,
  borderRadiusFull: 9999,
  opacityDisabled: 0.38,
  opacityHover: 0.8,
  opacityLoading: 0.6,
  zIndexDropdown: 100,
  zIndexModal: 1000,
  zIndexTooltip: 2000,
  durationFast: 150,
  durationNormal: 250,
  durationSlow: 400,
  easingIn: 'cubic-bezier(0.4, 0, 1, 1)',
  easingOut: 'cubic-bezier(0, 0, 0.2, 1)',
  easingInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
  lineHeightTight: 1.25,
  lineHeightNormal: 1.5,
  lineHeightRelaxed: 1.75,
  breakpointSm: 640,
  breakpointMd: 768,
  breakpointLg: 1024,
  breakpointXl: 1280,
  foreground: '#111827',
  background: '#FFFFFF',
  link: '#4340EA',
  linkHover: '#3533C4',
  selection: '#EEEDFE',
  focusRing: '#4340EA',
  focusRingWidth: 2,
  focusRingOffset: 2,
  fontFamilySans: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  fontFamilyMono: "'JetBrains Mono', 'Fira Code', 'SF Mono', Consolas, monospace",
  containerSm: 480,
  containerMd: 768,
  containerLg: 1024,
  containerXl: 1280,
  columnCount: 12,
  gutterWidth: 16,
  buttonHeightSm: 28,
  buttonHeightMd: 36,
  buttonHeightLg: 44,
  buttonPaddingX: 16,
  buttonRadius: 6,
  buttonFontSize: 14,
  buttonFontSizeSm: 13,
  buttonFontSizeLg: 16,
  inputHeightSm: 32,
  inputHeightMd: 36,
  inputHeightLg: 44,
  inputPaddingX: 12,
  toggleWidth: 48,
  toggleHeight: 24,
  toggleWidthSm: 36,
  toggleHeightSm: 20,
  toggleWidthLg: 60,
  toggleHeightLg: 30,
  badgeHeightSm: 18,
  badgeHeightMd: 22,
  badgeHeightLg: 28,
  badgePaddingX: 8,
  badgeFontSize: 11,
  tabActiveBg: '#4340EA',
  tabInactiveBg: '#F5F5F5',
  tabActiveText: '#FFFFFF',
  tabInactiveText: '#666666',
  tabHeight: 40,
  tabGap: 0,
  tabIndicatorHeight: 3,
  listItemHeight: 44,
  listItemGap: 1,
  listItemPaddingX: 16,
  listIconSize: 20,
  menuItemHeight: 32,
  menuItemPaddingX: 12,
  menuDividerColor: '#E8E8E8',
  menuDividerMargin: 8,
  listDividerColor: '#E8E8E8',
  menuCornerRadius: 8,
  menuShadow: true,
  progressHeight: 6,
  progressTrackColor: '#E8E8E8',
  progressFillColor: '#4340EA',
  progressCornerRadius: 3,
  sliderTrackHeight: 4,
  sliderTrackColor: '#E0E0E0',
  sliderFillColor: '#4340EA',
  sliderHandleSize: 20,
  sliderHandleColor: '#FFFFFF',
  sliderHandleBorder: '#4340EA',
  breadcrumbSeparator: '/',
  breadcrumbSeparatorColor: '#999999',
  breadcrumbFontSize: 13,
  tooltipBg: '#333333',
  tooltipTextColor: '#FFFFFF',
  tooltipFontSize: 12,
  tooltipPadding: 8,
  tooltipCornerRadius: 4,
  dividerColor: '#E0E0E0',
  dividerThickness: 1,
  dividerLabelBg: '#FFFFFF',
  dividerLabelColor: '#999999',
  tagDefaultBg: '#F5F5F5',
  tagDefaultText: '#333333',
  tagPrimaryBg: '#F4F3FF',
  tagPrimaryText: '#4340EA',
  tagSuccessBg: '#E6F7E6',
  tagSuccessText: '#1A7D1A',
  tagWarningBg: '#FFF3E0',
  tagWarningText: '#92400E',
  tagDangerBg: '#FFEBEE',
  tagDangerText: '#C62828',
  tagHeight: 28,
  tagPaddingX: 12,
  tagFontSize: 13,
  tagCornerRadius: 6,
  tagClosableSize: 14,
  spinnerSize: 32,
  spinnerStrokeWidth: 3,
  spinnerColor: '#4340EA',
  spinnerTrackColor: '#E8E8E8',
  modalOverlay: '#00000080',
  modalWidth: 400,
  modalCornerRadius: 16,
  modalPadding: 24,
  modalFooterBorder: '#E8E8E8',
  alertWidth: 380,
  alertCornerRadius: 8,
  alertIconSize: 20,
  alertSuccessBg: '#E6F7E6',
  alertSuccessBorder: '#B7EBB7',
  alertSuccessIcon: '#1A7D1A',
  alertWarningBg: '#FFF8E1',
  alertWarningBorder: '#FFE082',
  alertWarningIcon: '#92400E',
  alertErrorBg: '#FFEBEE',
  alertErrorBorder: '#FFCDD2',
  alertErrorIcon: '#C62828',
  alertInfoBg: '#E3F2FD',
  alertInfoBorder: '#BBDEFB',
  alertInfoIcon: '#1565C0',
  paginationBtnSize: 36,
  paginationActiveBg: '#4340EA',
  paginationActiveText: '#FFFFFF',
  paginationBtnBg: 'transparent',
  paginationBtnText: '#374151',
  paginationBtnCornerRadius: 6,
  paginationBtnGap: 4,
  stepSize: 32,
  stepConnectorColor: '#E0E0E0',
  stepActiveColor: '#4340EA',
  stepCompletedColor: '#4340EA',
  stepInactiveColor: '#D0D5DD',
  stepInactiveText: '#999999',
  stepFontSize: 13,
  accordionHeaderHeight: 48,
  accordionContentPadding: 16,
  accordionBorderColor: '#E8E8E8',
  accordionCornerRadius: 8,
  accordionGap: 0,
}

const SCALE_BINDINGS: Record<string, string> = {
  buttonRadius: 'borderRadiusLg',
  tagCornerRadius: 'borderRadiusLg',
  componentCornerRadius: 'borderRadiusMd',
  radioCornerRadius: 'borderRadiusXl',
  containerCornerRadius: 'borderRadiusXl',
  tooltipCornerRadius: 'borderRadiusSm',
  paginationBtnCornerRadius: 'borderRadiusMd',
  modalCornerRadius: 'borderRadiusXl',
  accordionCornerRadius: 'borderRadiusMd',
  alertCornerRadius: 'borderRadiusMd',
  sliderHandleSize: 'borderRadiusFull',
}

function deriveDarkTokens(brand: string): Record<string, any> {
  return {
    foreground: '#E4E4E7',
    background: '#131426',
    link: brand,
    linkHover: brand + 'CC',
    selection: brand + '33',
    focusRing: brand,
    bgWhite: '#1A1B2E',
    bgDisabled: '#2A2B3E',
    bgDisabledChecked: '#3A3B4E',
    textPrimary: '#E4E4E7',
    textTitle: '#FFFFFF',
    textDisabled: '#71717A',
    textBrand: brand,
    border: '#3F3F50',
    borderHover: brand,
    borderDisabled: '#2A2B3E',
    modalOverlay: '#00000080',
    shadowColor: '#00000060',
    tabActiveBg: brand,
    tabInactiveBg: '#27283A',
    tabActiveText: '#FFFFFF',
    tabInactiveText: '#A1A1AA',
    menuDividerColor: '#3F3F50',
    listDividerColor: '#3F3F50',
    progressTrackColor: '#3F3F50',
    sliderTrackColor: '#3F3F50',
    breadcrumbSeparatorColor: '#71717A',
    tooltipBg: '#27283A',
    tooltipTextColor: '#E4E4E7',
    dividerColor: '#3F3F50',
    tagDefaultBg: '#27283A',
    tagDefaultText: '#E4E4E7',
    tagPrimaryBg: brand + '33',
    tagPrimaryText: brand,
    accordionBorderColor: '#3F3F50',
    spinnerTrackColor: '#3F3F50',
    checkMark: '#FFFFFF',
    checkMarkDisabled: '#71717A',
    stepConnectorColor: '#3F3F50',
    stepInactiveColor: '#3F3F50',
    stepInactiveText: '#71717A',
    paginationBtnText: '#E4E4E7',
    alertSuccessBg: '#0D3B0D',
    alertSuccessBorder: '#1A6B1A',
    alertWarningBg: '#3B2E00',
    alertWarningBorder: '#6B5A00',
    alertErrorBg: '#3B0D0D',
    alertErrorBorder: '#6B1A1A',
    alertInfoBg: '#0D2B3B',
    alertInfoBorder: '#1A5A6B',
    toastSuccessBg: '#0D3B0D',
    toastWarningBg: '#3B2E00',
    toastErrorBg: '#3B0D0D',
    toastInfoBg: '#0D2B3B',
  }
}

export function mergeTheme(userTheme: any): any {
  if (!userTheme) return { ...DEFAULT_THEME }
  const t = { ...DEFAULT_THEME }
  for (const k of Object.keys(t)) {
    if (userTheme[k] !== undefined) t[k] = userTheme[k]
  }
  if (userTheme.mode === 'dark') {
    const darkTokens = deriveDarkTokens(t.brand)
    for (const k of Object.keys(darkTokens)) {
      if (userTheme[k] === undefined) t[k] = darkTokens[k]
    }
  }
  for (const [compKey, scaleKey] of Object.entries(SCALE_BINDINGS)) {
    if (userTheme[scaleKey] !== undefined && userTheme[compKey] === undefined) {
      t[compKey] = t[scaleKey]
    }
  }
  const brand = userTheme.brand !== undefined ? userTheme.brand : t.brand
  const derivativeTokens: Record<string, string> = {
    progressFillColor: brand,
    sliderFillColor: brand,
    sliderHandleBorder: brand,
    tabActiveBg: brand,
    stepActiveColor: brand,
    stepCompletedColor: brand,
    spinnerColor: brand,
    tagPrimaryText: brand,
    borderHover: brand,
    paginationActiveBg: brand,
    brandLight: brand + '1A',
  }
  for (const [key, value] of Object.entries(derivativeTokens)) {
    if (userTheme[key] === undefined) {
      t[key] = value
    }
  }
  return t
}
